# Generated by Django 4.2.7 on 2023-11-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="stars",
            field=models.CharField(
                choices=[
                    ("1", "Very Bad"),
                    ("2", "Bad"),
                    ("3", "Normal"),
                    ("4", "Good"),
                    ("5", "Perfect"),
                ],
                max_length=10,
            ),
        ),
    ]
