# Generated by Django 4.2.7 on 2023-11-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_comment_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="product/product_cover/",
                verbose_name="Product Image",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(verbose_name="Comment Text"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="stars",
            field=models.CharField(
                choices=[
                    ("1", "Very Bad"),
                    ("2", "Bad"),
                    ("3", "Normal"),
                    ("4", "Good"),
                    ("5", "Perfect"),
                ],
                max_length=10,
                verbose_name="What is your score?",
            ),
        ),
    ]
