# Generated by Django 4.2.7 on 2023-11-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_comment_image_alter_comment_body_alter_comment_stars"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="product/product_cover/",
                verbose_name="Product Image",
            ),
        ),
    ]
