# Generated by Django 4.2.7 on 2023-11-07 10:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_remove_comment_image_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
